In [1]:
import pandas as pd

In [9]:
df = pd.read_csv("datasets\Training.csv")
df.head()

<>:1: SyntaxWarning: invalid escape sequence '\T'
<>:1: SyntaxWarning: invalid escape sequence '\T'
C:\Users\My pc\AppData\Local\Temp\ipykernel_5016\2125478647.py:1: SyntaxWarning: invalid escape sequence '\T'
  df = pd.read_csv("datasets\Training.csv")


FileNotFoundError: [Errno 2] No such file or directory: 'datasets\\Training.csv'

In [ ]:
df.shape

(4920, 133)

In [ ]:
len(df['prognosis'].unique())

41

In [ ]:
df['prognosis'].unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [ ]:
X = df.drop('prognosis', axis = 1)
Y = df['prognosis']

In [ ]:
le = LabelEncoder()
le.fit(Y)
y = le.transform(Y)
y

array([15, 15, 15, ..., 38, 35, 27])

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size = 0.3, random_state = 20)

In [ ]:
X_train.shape, X_test.shape, Y_train.shape,Y_test.shape

((3444, 132), (1476, 132), (3444,), (1476,))

In [ ]:
Y_train, Y_test

(array([37, 34, 29, ..., 40, 20, 20]), array([40,  6, 16, ...,  8, 10, 33]))

In [ ]:
from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np


In [ ]:
model_result = {
    'SVC': SVC(kernel='linear'),
    'RandomForest': RandomForestClassifier(n_estimators=100, random_state=42),
    'GradientBoosting': GradientBoostingClassifier(n_estimators=100, random_state=42),
    'KNeighbors': KNeighborsClassifier(n_neighbors=5),
    'MultinomialNB': MultinomialNB()
}
for model_name, model in model_result.items():
    model.fit(X_train, Y_train)
    prediction = model.predict(X_test)
    accuracy = accuracy_score(Y_test, prediction)
    con_matrix = confusion_matrix(Y_test, prediction)
    print(f" {model_name} accuracy : {accuracy}")
    print(f"{model_name} confusion matrix :")
    print(np.array2string(con_matrix, separator = ',' ))




 SVC accuracy : 1.0
SVC confusion matrix :
[[40, 0, 0,..., 0, 0, 0],
 [ 0,43, 0,..., 0, 0, 0],
 [ 0, 0,28,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,34, 0, 0],
 [ 0, 0, 0,..., 0,41, 0],
 [ 0, 0, 0,..., 0, 0,31]]
 RandomForest accuracy : 1.0
RandomForest confusion matrix :
[[40, 0, 0,..., 0, 0, 0],
 [ 0,43, 0,..., 0, 0, 0],
 [ 0, 0,28,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,34, 0, 0],
 [ 0, 0, 0,..., 0,41, 0],
 [ 0, 0, 0,..., 0, 0,31]]
 GradientBoosting accuracy : 1.0
GradientBoosting confusion matrix :
[[40, 0, 0,..., 0, 0, 0],
 [ 0,43, 0,..., 0, 0, 0],
 [ 0, 0,28,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,34, 0, 0],
 [ 0, 0, 0,..., 0,41, 0],
 [ 0, 0, 0,..., 0, 0,31]]
 KNeighbors accuracy : 1.0
KNeighbors confusion matrix :
[[40, 0, 0,..., 0, 0, 0],
 [ 0,43, 0,..., 0, 0, 0],
 [ 0, 0,28,..., 0, 0, 0],
 ...,
 [ 0, 0, 0,...,34, 0, 0],
 [ 0, 0, 0,..., 0,41, 0],
 [ 0, 0, 0,..., 0, 0,31]]
 MultinomialNB accuracy : 1.0
MultinomialNB confusion matrix :
[[40, 0, 0,..., 0, 0, 0],
 [ 0,43, 0,..., 0, 0, 0],
 [ 0, 0

In [ ]:
svc  = SVC(kernel='linear')
svc.fit(X_train, Y_train)
svmpredict= svc.predict(X_test)
print(accuracy_score(Y_test, svmpredict))
print(confusion_matrix(Y_test, svmpredict))

1.0
[[40  0  0 ...  0  0  0]
 [ 0 43  0 ...  0  0  0]
 [ 0  0 28 ...  0  0  0]
 ...
 [ 0  0  0 ... 34  0  0]
 [ 0  0  0 ...  0 41  0]
 [ 0  0  0 ...  0  0 31]]


In [ ]:
import pickle
import os

# Create the 'models' directory if it doesn't exist
os.makedirs("models", exist_ok=True)

# Now, dump the model
pickle.dump(svc, open("models/svc.pkl", 'wb'))

In [ ]:
svc = pickle.load(open("models/svc.pkl", 'rb'))

In [ ]:
#test1
print("Predictedlabel : ", (svc.predict(X_test.iloc[0].values.reshape(1,-1))))
print("Predictedlabel : ", Y_test[0])

Predictedlabel :  [40]
Predictedlabel :  40


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [ ]:
#test2
print("predicted label : ", svc.predict(X_test.iloc[20].values.reshape(1,-1)))
print("actual label : ", Y_test[20])

predicted label :  [10]
actual label :  10


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [ ]:
symtoms = pd.read_csv("/content/symtoms_df.csv")
precaution = pd.read_csv("/content/precautions_df.csv")
description = pd.read_csv("/content/description.csv")
medications = pd.read_csv("/content/medications.csv")
diets = pd.read_csv("/content/diets.csv")
workout = pd.read_csv("/content/workout_df.csv")

In [ ]:
def suggested_func(final_diseases):
    descrp = description[description['Disease'] == final_diseases]['Description']
    descrp = " ".join([total for total in descrp])

    prec = precaution[precaution['Disease'] == final_diseases][['Precaution_1', 'Precaution_2', 'Precaution_3', 'Precaution_4']]
    prec = [all for all in prec.values]

    medi = medications[medications["Disease"] == final_diseases]["Medication"]
    medi = [all for all in medi.values]

    diet = diets[diets['Disease'] == final_diseases]['Diet']
    diet = [all for all in diet.values]

    work = workout[workout['disease'] == final_diseases]['workout']

    return descrp,prec,medi,diet,work




symptoms_dict = {'itching': 0, 'skin_rash': 1, 'nodal_skin_eruptions': 2, 'continuous_sneezing': 3, 'shivering': 4, 'chills': 5, 'joint_pain': 6, 'stomach_pain': 7, 'acidity': 8, 'ulcers_on_tongue': 9, 'muscle_wasting': 10, 'vomiting': 11, 'burning_micturition': 12, 'spotting_ urination': 13, 'fatigue': 14, 'weight_gain': 15, 'anxiety': 16, 'cold_hands_and_feets': 17, 'mood_swings': 18, 'weight_loss': 19, 'restlessness': 20, 'lethargy': 21, 'patches_in_throat': 22, 'irregular_sugar_level': 23, 'cough': 24, 'high_fever': 25, 'sunken_eyes': 26, 'breathlessness': 27, 'sweating': 28, 'dehydration': 29, 'indigestion': 30, 'headache': 31, 'yellowish_skin': 32, 'dark_urine': 33, 'nausea': 34, 'loss_of_appetite': 35, 'pain_behind_the_eyes': 36, 'back_pain': 37, 'constipation': 38, 'abdominal_pain': 39, 'diarrhoea': 40, 'mild_fever': 41, 'yellow_urine': 42, 'yellowing_of_eyes': 43, 'acute_liver_failure': 44, 'fluid_overload': 45, 'swelling_of_stomach': 46, 'swelled_lymph_nodes': 47, 'malaise': 48, 'blurred_and_distorted_vision': 49, 'phlegm': 50, 'throat_irritation': 51, 'redness_of_eyes': 52, 'sinus_pressure': 53, 'runny_nose': 54, 'congestion': 55, 'chest_pain': 56, 'weakness_in_limbs': 57, 'fast_heart_rate': 58, 'pain_during_bowel_movements': 59, 'pain_in_anal_region': 60, 'bloody_stool': 61, 'irritation_in_anus': 62, 'neck_pain': 63, 'dizziness': 64, 'cramps': 65, 'bruising': 66, 'obesity': 67, 'swollen_legs': 68, 'swollen_blood_vessels': 69, 'puffy_face_and_eyes': 70, 'enlarged_thyroid': 71, 'brittle_nails': 72, 'swollen_extremeties': 73, 'excessive_hunger': 74, 'extra_marital_contacts': 75, 'drying_and_tingling_lips': 76, 'slurred_speech': 77, 'knee_pain': 78, 'hip_joint_pain': 79, 'muscle_weakness': 80, 'stiff_neck': 81, 'swelling_joints': 82, 'movement_stiffness': 83, 'spinning_movements': 84, 'loss_of_balance': 85, 'unsteadiness': 86, 'weakness_of_one_body_side': 87, 'loss_of_smell': 88, 'bladder_discomfort': 89, 'foul_smell_of urine': 90, 'continuous_feel_of_urine': 91, 'passage_of_gases': 92, 'internal_itching': 93, 'toxic_look_(typhos)': 94, 'depression': 95, 'irritability': 96, 'muscle_pain': 97, 'altered_sensorium': 98, 'red_spots_over_body': 99, 'belly_pain': 100, 'abnormal_menstruation': 101, 'dischromic _patches': 102, 'watering_from_eyes': 103, 'increased_appetite': 104, 'polyuria': 105, 'family_history': 106, 'mucoid_sputum': 107, 'rusty_sputum': 108, 'lack_of_concentration': 109, 'visual_disturbances': 110, 'receiving_blood_transfusion': 111, 'receiving_unsterile_injections': 112, 'coma': 113, 'stomach_bleeding': 114, 'distention_of_abdomen': 115, 'history_of_alcohol_consumption': 116, 'fluid_overload.1': 117, 'blood_in_sputum': 118, 'prominent_veins_on_calf': 119, 'palpitations': 120, 'painful_walking': 121, 'pus_filled_pimples': 122, 'blackheads': 123, 'scurring': 124, 'skin_peeling': 125, 'silver_like_dusting': 126, 'small_dents_in_nails': 127, 'inflammatory_nails': 128, 'blister': 129, 'red_sore_around_nose': 130, 'yellow_crust_ooze': 131}
diseases_list = {15: 'Fungal infection', 4: 'Allergy', 16: 'GERD', 9: 'Chronic cholestasis', 14: 'Drug Reaction', 33: 'Peptic ulcer diseae', 1: 'AIDS', 12: 'Diabetes ', 17: 'Gastroenteritis', 6: 'Bronchial Asthma', 23: 'Hypertension ', 30: 'Migraine', 7: 'Cervical spondylosis', 32: 'Paralysis (brain hemorrhage)', 28: 'Jaundice', 29: 'Malaria', 8: 'Chicken pox', 11: 'Dengue', 37: 'Typhoid', 40: 'hepatitis A', 19: 'Hepatitis B', 20: 'Hepatitis C', 21: 'Hepatitis D', 22: 'Hepatitis E', 3: 'Alcoholic hepatitis', 36: 'Tuberculosis', 10: 'Common Cold', 34: 'Pneumonia', 13: 'Dimorphic hemmorhoids(piles)', 18: 'Heart attack', 39: 'Varicose veins', 26: 'Hypothyroidism', 24: 'Hyperthyroidism', 25: 'Hypoglycemia', 31: 'Osteoarthristis', 5: 'Arthritis', 0: '(vertigo) Paroymsal  Positional Vertigo', 2: 'Acne', 38: 'Urinary tract infection', 35: 'Psoriasis', 27: 'Impetigo'}
def predicted_values(patient_symptoms):
    input_symptoms = np.zeros(len(symptoms_dict))
    for item in patient_symptoms:
        input_symptoms[symptoms_dict[item]]=1
    return diseases_list[svc.predict([input_symptoms])[0]]




In [ ]:
symptoms = input("Enter your Symptoms =>")
user_symptoms = [s.strip() for s in symptoms.split(',')]
user_symptoms = [symp.strip("[] , ") for symp in user_symptoms]
predicted_Diseases = predicted_values(user_symptoms)
descrp,prec,medi,diet,work = suggested_func(predicted_Diseases)


print(".....................PREDICTED DISEASE......................")
print(predicted_Diseases)
print("......................DESCRIPTION............................")
print(descrp)
print("......................PRECAUTIONS............................")
i = 1
for p in prec[0]:
    print(i, ": ", p)
    i += 1

print("......................MEDICATIONS...........................")
for m in medi:
    print(i, ": ", m)
    i += 1

print("........................WORKOUT..............................")
for w in work:
    print(i, ": ", w)
    i += 1

print("...........................DIETS.............................")
for d in diet:
    print(i, ": ", d)
    i += 1




Enter your Symptoms =>itching, skin_rash,chills
.....................PREDICTED DISEASE......................
Fungal infection
......................DESCRIPTION............................
Fungal infection is a common skin condition caused by fungi.
......................PRECAUTIONS............................
1 :  bath twice
2 :  use detol or neem in bathing water
3 :  keep infected area dry
4 :  use clean cloths
......................MEDICATIONS...........................
5 :  ['Antifungal Cream', 'Fluconazole', 'Terbinafine', 'Clotrimazole', 'Ketoconazole']
........................WORKOUT..............................
6 :  Avoid sugary foods
7 :  Consume probiotics
8 :  Increase intake of garlic
9 :  Include yogurt in diet
10 :  Limit processed foods
11 :  Stay hydrated
12 :  Consume green tea
13 :  Eat foods rich in zinc
14 :  Include turmeric in diet
15 :  Eat fruits and vegetables
...........................DIETS.............................
16 :  ['Antifungal Diet', 'Probiotics',

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [ ]:
import sklearn
print(sklearn.__version__)

1.6.1
